### ISSUE TITLE
Camp.js IX/2017

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#1]
Apologies if this has kicked off elsewhere. I'm sure our fearless leader @DamonOehlman is on top of things but how can I and other's help?

**Comment by DamonOehlman** [comment]
Hey Glen - I've stepped back for this one.  Though I know Craig Sharkie is on the case, and we've had some interest for hosting the next one in NZ :)

**Comment by garrows** [comment]
Sorry to see you go. Thank you for putting on a great campjs.
