### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#10]
We should compile an inventory list. 

@timoxley believes most of it is with @digitalcraft in Brisbane. 
@eugeneware perhaps has some in Melbourne. 
@AnnaGerber has some robotics/electronics/IoT stuff.
@iamkevinv might have or know the location of some more stuff. 
@joshwnj has 2 Aldi pod coffee machines in Melbourne.

**Comment by SomeoneWeird** [comment]
cc @digitalcraft

**Comment by digitalcraft** [comment]
WRT networking equipment. I'm generally the caretaker of it.
I've recently loaned it out to Rails Camp via (Tom Ridge)

**Comment by AnnaGerber** [comment]
Yes, from memory there are around 15 Arduino starter kits that are with the NodeBots BNE gear

**Comment by garrows** [comment]
@digitalcraft is also the caretaker of the power boards & extension leads also loaned out to Rails Camp.
