### ISSUE TITLE
Internet

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#11]
I present a copy/paste from @timoxley: 

The last Melbourne camp was run entirely off 4G. We pulled down ~300 gigabytes over the weekend. Remarkably, this single 4G connection was able to provide decent internet service to the entire camp. We did block a bunch of things to help reduce the load, like video streaming and backup services and there was an annoying limitation imposed by the 4G carrier that meant we had to restart the modem after every 3 gigabytes, but otherwise it worked adequately.

At that camp, the 4G signal was bad at ground level so we put the modem in the tower then ran a wireless link across to the hall. Apparently the device  providing that wireless link had an 8km range, so long as there was a physical line of sight in-between the two endpoints.

Thus I've thought perhaps one strategy could be to beam internet into the venue from somewhere that has better reception. e.g. a nearby hill

Note I'd hired a professional to handle the internet/network at that event, and they came with specialist equipment. This wasn't cheap and perhaps isn't worth the hassle/expense for future camps.

Also of note: that 300GB of internet was provided by a prepaid $50 4G data sim card. There just happened to be a deal on for "unlimited weekend data". We probably very much broke the terms and conditions of that offer but whatever.

**Comment by SomeoneWeird** [comment]
@digitalcraft ran internet at our last camp and did a fantastic job. We should try and see if he's available again to help out

**Comment by digitalcraft** [comment]
I'm currently available to do this and can confirm this when dates are released.

**Comment by garrows** [comment]
Thank you very much @digitalcraft. Confirmed from slack for those watching at home.

**Comment by garrows** [comment]
Reopened this as I'd like to add some more.

One event @alexiamcdonald fell down some stairs and wasn't able to contact anyone via phone or wifi and had to wait 10 minutes before someone heard her.  https://github.com/campjs/campjs-next/issues/52#issuecomment-313036406

We should make a big effort this year to ensure that even the dorms are covered by wifi. 

We should also have a way on the local intranet to contact the organisers in case of emergency that doesn't require any downloads to use. Not sure what this could be so I've opened an issue looking for suggestions.
