### ISSUE TITLE
Pay Invoice: Venue Deposit

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#12]
Hey @DamonOehlman. I'll try to see the bank ASAP about organising a joint account but in the meantime could you please pay the following invoice.

```
Lord Somers Camp
BSB: 013006
Acc No: 005387419
Reference: 1812
$3154.00
```

Record kept here:
https://github.com/campjs/campjs-next/blob/gh-pages/org/invoices.json#L3-L13

**Comment by DamonOehlman** [comment]
Sure thing, I'll take care of that today :)

**Comment by DamonOehlman** [comment]
Done.
