### ISSUE TITLE
Childcare

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#18]
I saw today that pyconau is providing childcare for a fee (and conflicts with our dates 😭) 
https://twitter.com/pyconau/status/856992718269984768
which is an amazing idea and I think we should follow suit.

We need to:
- Find qualified childcare services
- Cost to ticket holders 
- How to charge
- Announcements/Information

Thoughts?

**Comment by cathylill** [comment]
Googled some providers:
http://www.dialanangel.com/child-care/creche-services
http://www.crechendo.com.au/
http://abrachild.com.au/events-mobile-pop-up-creche/
http://nannies.charltonbrown.com.au/our-services/corporate-creche/

Does anyone know who pycon are using?

**Comment by garrows** [comment]
Thanks @cathylill! Really appreciate it. Any looking particularly good?

**Comment by cathylill** [comment]
No idea really but I'm happy to send off some emails if you like?

**Comment by garrows** [comment]
I'd really like that 😀. Momentum is faster than expected so really need help.

**Comment by developersteve** [comment]
Actually i know someone (whos a qualified child care professional) from the localhostbne org team that might be interested in doing it for flights and acom. Just depends on numbers as to how many people will be needed.

**Comment by cathylill** [comment]
@developersteve cool sounds like it'd be worth asking. @garrows might be worth checking with the venue if they have any legal or insurance requirements for on-site carers. I noticed some providers mentioned that they have their own public liability insurance, carers have working with children / police checks etc.

**Comment by garrows** [comment]
I asked about the insurance from the venue and got this back

"Regarding our insurance coverage, our policy won’t cover your child care professional as it is a contractor/service provider you have engaged yourself and not a service we are providing ourselves.
Our insurance will cover any injury caused as a result of normal use of the facility but it won’t protect you against any unsuitable conduct by your participants or private service providers." 

So we should make sure the carer has proper insurance. 

Regarding the someone that @developersteve mentioned, I contacted him and he doesn't have the insurance or a collection of toys/activities to entertain the kids so he recommended we go with a professional service.

How are you going with gathering quotes @cathylill? Thanks again for helping out 😄

**Comment by garrows** [comment]
Here is the insurance policy if you're interested https://github.com/campjs/campjs-next/blob/gh-pages/org/melbourne/Policy-03.080.0269438.pdf

**Comment by cathylill** [comment]
Hey everyone, sorry been a bit busy the last couple weeks but got one reply back so far from Abracadabra Childcare Services as follows:

$40 daily fee per carer + $40 per hour per carer (minimum 2 carers, 4hrs)
0-2 years - 3 children per carer
3-6 years - 5 children per carer
7+ years - 7 children per carer

'Activities' materials such as toys, books, play mats, cushions etc is $15 extra per child per day  + $40 to cover one carer's time to unpack / pack up.

We need to provide them with:
- Baby change table/floor mat area
- Prams for napping if needed and authorized by parents
- Microwave for heating milk/bottles
- Fridge
- TV/DVD Player
- Tables & Chairs
- Water
- Plastic cups/serviettes
- First Aid Kit
- Bathrooms
- Onsite induction : Floor Plan, Fire Exits etc
- Snacks and Lunch for Children 

I'll post any more replies as they come in :)

**Comment by cathylill** [comment]
Oh I just realised that carer's per hour rate is GST free but booking fee and activities is +GST, so, say we had the creche 10am - 12pm and 2pm - 4pm both days for 8 - 10 kids it'd cost:
$728 (incl GST) for just the carers
+
$410 (incl GST) for activities materials

**Comment by garrows** [comment]
Thanks so much for putting this together @cathylill. 

If we were to get 10 kids we'd have to charge $110 each kid which seems like a lot and its risky if we only get a few. Getting a sponsor to cover costs would be much better I think so I'll put the call out.

**Comment by cathylill** [comment]
@garrows this might be of interest to you https://medium.com/leaky-abstractions/conference-childcare-part-1-helpful-thoughts-for-conference-organizers-203d2b34df5b
