### ISSUE TITLE
Family tickets

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#19]
Family tickets have been requested in the view-source slack by @cathy_l and @bguiz. I personally would also like to see this happen. 

https://viewsource.slack.com/messages/C0EBLFDE1/convo/C0EBLFDE1-1493777742.253274/ 

Some copy + paste while the slack history remains

Cathy:
```
I’m not sure if I will be able to make it this time, but if there is childminding gotta have some kind of accom suitable for families. last time at Lord Summers there was family rooms in the same building as the ladies dorms but don’t know what the ticketing arrangements were or the exact setup, i think it was just one couple that brought a baby that year.
```

Activities are hard to come by but its a nice spot to relax. 

1. Ticket price/prices? Most of the ticket is accomodation + food. Perhaps separate prices depending on age?
2. Should we exclude alcohol and coffee to lower the costs?
3. Double check the rooms with the venue, how many, size, etc?
4. What activities?

**Comment by bguiz** [comment]
5. Nearby things to do, sightseeing etc, and transport options for them

Doesn't have to be organised by campjs, just would be good to know what existing options there are in the area

**Comment by garrows** [comment]
As @bguiz said in slack, excluding alcohol and coffee would make other people want a cheaper ticket if they didn't drink them so that was a bad idea.

**Comment by cathylill** [comment]
I would do pricing like:
- Parents buy regular tickets to keep it simple and fair.
- Kids under 2 free (no childminding, parents to provide port-a-cot)
- Kids ticket for > 2yrs (venue kids p/n rate + childminding fee?)

Ask people to organise family accom options with you before booking so you can allocate rooms as you go. Last camp at Lord Somers there were family rooms in the same building that the ladies dorms were in which seemed to be a good setup as it was quieter and there were bathrooms inside that building. 

If there will be some older kids and non tech partners maybe could invite folks to submit some 'learn to code' talks and kids coding activities in the CFP?

**Comment by garrows** [comment]
@cathylill also suggested daytime only tickets in slack and kids tickets. I'll have to talk to the venue for pricing.
