### ISSUE TITLE
CampJS VIII

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#2]
Good news everybody. We are getting the Camp.js show back on the road. Nothing is booked in yet but we are aiming for **Melbourne/Lord Somers Camp, August 4th - 7th.**

There has been some organisation in the past on slack but we are moving back to github in an effort to keep things open and encourage community help/collaboration.

The main areas to organise at this point are:

- [x] Venue https://github.com/campjs/campjs-next/issues/3
- [x] Tickets https://github.com/campjs/campjs-next/issues/4
- [ ] Sponsors https://github.com/campjs/campjs-next/issues/5
- [x] Website https://github.com/campjs/campjs-next/issues/6
- [x] Transport/Buses https://github.com/campjs/campjs-next/issues/7

There has been some work in setting up a JSAU organisation. It's not a blocking issue for the next camp.js as we are considered an ["unincorporated organisation"](https://www.ourcommunity.com.au/management/view_help_sheet.do?articleid=2101) so we will continue without it. 

Camp.js doesn't happen without its community. I hope you're all excited about the next one and can lend a hand where you can.

**Comment by AnnaGerber** [comment]
Why CampJS-IX? What happened to CampJS-VIII? (Wasn't Sydney VII?)

**Comment by KoryNunn** [comment]
Yep, it's been fixed, the sub domain is correct.

**Comment by SomeoneWeird** [comment]
@garrows got a little ahead of himself ;)
