### ISSUE TITLE
CampJS zine

### ISSUE THREAD

**Issue by AnnaGerber** [campjs/campjs-next#22]
Here is an idea I was discussing with @iamkevinv 

I think it would be cool to put together a CampJS zine - we could put a call out for people to submit content, craft it together into a zine, and then print a small run for people to take home with them as a memento

Thoughts?

**Comment by iamkevinv** [comment]
+1 would zine more

**Comment by DamonOehlman** [comment]
Such a cool idea!

**Comment by AnnaGerber** [comment]
Here's a call for contribution for BrisJS or anyone else who wants to spread the word:

Submit stuff for the CampJS Zine!
With CampJS coming up in August and I think it would be cool to put together a Zine and print a small run for anyone who wants a copy to take home with them. [What’s a Zine? See https://en.wikipedia.org/wiki/Zine]

We need content to make this happen, so if you would like to share any CampJS (or general JS-related) memories, anecdotes, doodles. jokes, rules for werewolf or anything else you think should go in the zine, please head on over to the campjs-next GitHub repository and let me know by commenting on the issue (or email me directly at anna.m.gerber@gmail.com - Your contributions can be published anonymously if you wish). If you want to get involved with the editing / production process, that would also be awesome.

The link to the issue:
[https://github.com/campjs/campjs-next/issues/22](https://github.com/campjs/campjs-next/issues/22)

**Comment by AshKyd** [comment]
I put together some random tips for working offline: https://gist.github.com/AshKyd/3cffe04037956913db1ebd00aa0a0aa3

Pull requests/vociferous editing welcome.

Edit: what are you planning to lay it out with? It might be fun to put it together in HTML using print stylesheets, I reckon it would be novel. I'll have a play if I get some time, see what that would involve :D

Edit also: do you have an illustrator?

**Comment by AnnaGerber** [comment]
Awesome, thanks!

I was thinking pens, scissors, paper and glue + scanner or photocopier :)
Part of the appeal is focusing on the content and not on the tech

Otherwise in the past I have used Comic Life or Affinity Designer.  I used to use print stylesheets for producing eBooks & documents when I was working with Digital Editions / literature. They work ok for text-heavy stuff but it would be interesting to see how it works for graphic/comic style stuff.

I'm hoping that people will contribute their own comics / drawings, as well as using CC-licensed illustrations and I'll probably draw some stuff too.

btw here's a documentary that shows more about zines for anyone who isn't familiar with the idea:
https://vimeo.com/11386025

**Comment by lillypiri** [comment]
Happy to contribute illustration for this!

**Comment by AshKyd** [comment]
Bumping this one, I've sent some top secret illustrations to privately to Anna because I want it to be a surprise

Also I think @jwulf agreed to submit a two-page spread for Magikcraft last night at BrisJS ^_^

**Comment by lillypiri** [comment]
Do you have a due date for submissions? I can try make mine this weekend :)

**Comment by AnnaGerber** [comment]
Ideally by the end of next week (14th July) to allow enough time for collation and printing

I can't wait to see what you've been working on!

**Comment by lillypiri** [comment]
Cool. Are the specs A5 size and black&white printing?

**Comment by AnnaGerber** [comment]
Yes. There's at least one 2-pager too, so if you want to spread the content across a couple of pages let me know

**Comment by AnnaGerber** [comment]
Submissions to the zine are now closed (unless you have already contacted me) so that we have enough time for editing and printing

**Comment by garrows** [comment]
Ok to close this?

**Comment by AnnaGerber** [comment]
Yep, a limited run of around 50 zines have been printed (due to suitcase size / weight limitations).
I can provide a PDF for anyone else who wants to print their own.
