### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#3]
I'll be attempting to lock in Lord Somers Camp in August next week. 

I understand they require a downpayment to lock it in. Hopefully we can get a weekend soft booked so we can raise some funds beforehand.

Any weekends I should avoid in August?

**Comment by garrows** [comment]
@timoxley you organised this for the last camp in Melbourne. Are you able to find how much they charged? Was payment required in full?

**Comment by garrows** [comment]
@twalve can you dump any details as well when you get a chance please?

**Comment by garrows** [comment]
We are tentatively booked from Fri, August 4, 2017 – Mon, August 7, 2017 which is when @twalve had setup. They are sending me all the details this afternoon for finalisation.

**Comment by garrows** [comment]
[General Conditions of Hire 2016.pdf](https://github.com/campjs/campjs-next/files/956964/General.Conditions.of.Hire.2016.pdf)
[Camp JS Aug 2017 Camp Booking Form.pdf](https://github.com/campjs/campjs-next/files/956965/Camp.JS.Aug.2017.Camp.Booking.Form.pdf)

**Comment by SomeoneWeird** [comment]
$31.5k less $12k in bank would be $160/person to breakeven just for venue

**Comment by garrows** [comment]
Without going into the red, it'd be $262.90 (inc GST) per person which includes meals and accommodation. Not bad at all in my opinion. 

I'll get the venue to fix up the contract with my contact details and I'll sign & pay the deposit ($3,154) ASAP.

**Comment by garrows** [comment]
Venue deposit paid. 

Signed booking form https://github.com/campjs/campjs-next/blob/gh-pages/org/invoices/Camp%20JS%20Aug%202017%20Camp%20Booking%20Form.pdf

Deposit payment receipt https://github.com/campjs/campjs-next/blob/gh-pages/org/receipts/Camp%20JS%20Aug%202017%20Deposit%20Payment%20Receipt.pdf
