### ISSUE TITLE
Copy website content

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#30]
Need a kind volunteer to copy the content (particularly the about page) into the new website. I'd recommend copying from http://v.campjs.com/ as that has Melbourne specific content. 

There is some transport specific content, copy that too as I'm keeping that pretty much the same.

**Comment by AshKyd** [comment]
np, will get to this on the weekend.

**Comment by garrows** [comment]
You're the greatest!

**Comment by AshKyd** [comment]
This isn't something I can do. There's a bunch of stuff that's wonky and I'm not familiar enough with React to fix/restyle it in the time I have.

Branch is here if someone wants to pick it up https://github.com/AshKyd/campjs-next/tree/content-migration

**Comment by garrows** [comment]
Thanks @AshKyd. I really appreciate the contribution you did though.
