### ISSUE TITLE
Swag

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#33]
There seems to be no consensus on peoples preference but here is the list of suggestions:

* Shirts
* Beanies
* Socks
* Blanket
* Thermos
* Fingerless coder gloves
* Scout style hexagonal merit badge
* LED lights/glowsticks
* waterproof bluetooth speaker & flashlight https://twitter.com/pjf/status/867533341888626688

Let me know if I've missed anything.  

Paige at psiscreenprinting.com.au has emailed me. They have done the CampJS swag in the past.

**Comment by developersteve** [comment]
LED lights (Those are cheapish) and possibly glowsticks

also something i spotted recently in the realm of cool swag is a Twilio bluetooth speaker and flashlight https://twitter.com/pjf/status/867533341888626688

**Comment by AnnaGerber** [comment]
Fingerless coder gloves were another suggestion

**Comment by AnnaGerber** [comment]
Oh, and scout style merit badges but hexagonal

**Comment by garrows** [comment]
Thanks @developersteve & @AnnaGerber

**Comment by developersteve** [comment]
Oh this is cool too, havent seen these before and they would be fairly cheap 

https://twitter.com/sitapati/status/873147584147320832

http://www.imprint5.com/au/collapsible-promotional-water-bottle-28-oz.html

**Comment by garrows** [comment]
In talks with Paige from PSI Screenprinting. Here are some prices. 

OPTION 1 - BLANKETS w/ EMBROIDERY
130 x Legend Life J648 Coral Fleece Blanket: $19.99 ea + gst
TOTAL: $2598.70 + gst
PLACE ORDER BY: JULY 12th
______

OPTION 2 - T-SHIRTS w/ 3 COL FRONT PRINT
130 x AS Colour 5001 Mens Staple Tee and 4002 Ladies Wafer Tee: $16.89 ea + gst
TOTAL: $2196.80 + gst
PLACE ORDER BY: JULY 12th

______

OPTION 3 - BEANIES w/ EMBROIDERY
130 x Parkar Design B001 Beanie: $13.95 ea + gst
TOTAL: $1813.50 + gst
PLACE ORDER BY: JULY 12th

______

OPTION 4 - MUGS w/ 3 COL PRINT (cartons of 24)
144 x Fitzroy Thermal Travel Mug: $12.03 ea + gst
TOTAL: $1731.60 + gst
PLACE ORDER BY: JULY 16th


Probably going with blankets. Here are some designs I came up with.

![blanket4](https://user-images.githubusercontent.com/205256/27458206-3c6010f4-57eb-11e7-93af-d3b5e56d8af8.png)
![blanket3](https://user-images.githubusercontent.com/205256/27458207-3c9e33c0-57eb-11e7-93ba-9451e32239a9.png)
![blanket2](https://user-images.githubusercontent.com/205256/27458208-3cdb296a-57eb-11e7-99a6-50acd2718cf0.png)

**Comment by AnnaGerber** [comment]
What are your thoughts on the swag being generically CampJS branded rather than having a specific number? (I really like that about generic stuff from previous camps like the multitool)

**Comment by developersteve** [comment]
Yeah thats a good idea and it opens up the possibility of things being sold outside of event planning, good way to help discount future camps!

**Comment by garrows** [comment]
Just brand it like the logo text? https://pbs.twimg.com/profile_images/557816711206801408/5HuhlQiL.png

**Comment by AnnaGerber** [comment]
Sounds good.

I still really like the idea of fabric badges/patches - how sweet would it be if each CampJS there was a camp-specific badge that you could sew onto your blanket?

**Comment by KoryNunn** [comment]
Throwing in my votes:

**Shirts** 
~Beanies~
~Socks~
~Blanket~
**Thermos**
~Fingerless coder gloves~
~Scout style hexagonal merit badge~
~LED lights/glowsticks~
~waterproof bluetooth speaker & flashlight https://twitter.com/pjf/status/867533341888626688~
**Mug** <- Top preference.

**Comment by thissophie** [comment]
Blanket, beanie or thermos gets my vote.

I also love the idea of badges for the blanket in future camps. 

T-shirts and mugs I already have way too many of :/

**Comment by garrows** [comment]
Good idea @AnnaGerber I'll ask for fabric badges too. 

Turns out they can only do the first design so I'll change it to the text from https://pbs.twimg.com/profile_images/557816711206801408/5HuhlQiL.png later tonight. 
Center align it will probably look better too.

I'll probably get a limited run of shirts and/or mugs too depending on the budget at the end. Blankets will be the minimum though.

**Comment by garrows** [comment]
Some new designs
![badge](https://user-images.githubusercontent.com/205256/27515400-8408d62e-59e5-11e7-8f1d-0f91731c3364.png)
![badge-inv](https://user-images.githubusercontent.com/205256/27515398-8404c502-59e5-11e7-8ded-86cf42c530c1.png)
![blanket-a](https://user-images.githubusercontent.com/205256/27515397-84046800-59e5-11e7-8bf4-83524202db50.png)
![blanket-b](https://user-images.githubusercontent.com/205256/27515399-840680fe-59e5-11e7-904b-f6aac7f18d0a.png)
![blanket-c](https://user-images.githubusercontent.com/205256/27515396-840071d2-59e5-11e7-980d-481fbca8e763.png)

**Comment by garrows** [comment]
I've ordered 200 badges & 170 blankets.

I think I'll scrap the idea of getting shirts as well. Cuts too much into the budget.

**Comment by garrows** [comment]
Ordered and paid for. Shipping to @marcosc's office to bring to the camp.
No shirts :cry:
