### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#4]
Note we don't have a date locked in until https://github.com/campjs/campjs-next/issues/3 is done but the setup can begin.

In the past we have used https://ti.to which has worked well but are there any newer services that charge less?

**Comment by SomeoneWeird** [comment]
We got in contact with ti.to last time and they offered to give us a discount the next time, we should def look into using that if we end up going with them again

**Comment by garrows** [comment]
Regarding pricing, the venue will cost $262.90 per person.

From the camps I attended and could find receipts for:
III - Melb - $376 (Alumni discount)
IV - Bris - $290 (Early Early Early Bird)
V - Melb - $320 (Early Early Early Bird)
VI - Bris - $330 (Full price?)
VII - Syd - $350 (Early Bird)

At this point I don't have pricing/estimates on shirts, alcohol, buses, sponsors, etc so based on history and intuition I'd like to release 30 Early Early Early Bird tickets at $320. Hopefully we can have them up for sale by the weekend. 

That depends on the deposit being paid on https://github.com/campjs/campjs-next/issues/3 and at least a landing site done on https://github.com/campjs/campjs-next/issues/6.

**Comment by garrows** [comment]
Early Early Early Bird ticket is up
https://ti.to/campjs/campjs-viii

**Comment by garrows** [comment]
The tickets are selling well. 20 of 30 sold. 
I plan to release 'early early bird'  tickets after 5 talks are locked in.

**Comment by garrows** [comment]
54 tickets sold so far.
