### ISSUE TITLE
Sponsors Page

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#48]
We need to add a sponsors page to the website. 

At the moment we have Lookahead search confirmed as the coffee sponsor. Digital8 is the internet/network sponsor. 

I've also told the speakers if their company pays for them to come, they are added to the sponsors list too. So far its only Seer Medical (https://seermedical.com/) sending Robert Kerr.

Check https://github.com/campjs/campjs-next/issues/5 for the official list.

**Comment by twalve** [comment]
I'll take a look! Should be the same requirements as the Team page.

Do you fancy adding me to the organisation in anticipation? :)

**Comment by garrows** [comment]
@twalve I thought you already were. I've added you now.

**Comment by garrows** [comment]
Also, thanks for working on this!

**Comment by garrows** [comment]
@twalve you need to accept organisation invites these days. You should have an email or just go to https://github.com/campjs to accept.

**Comment by jwulf** [comment]
Just Digital People are sending The Legendary Josh Wulf™ - As Seen on the Internet®. Can we add them to the sponsors' page, please?

**Comment by jwulf** [comment]
![jdp - sponsored by](https://user-images.githubusercontent.com/406975/28051778-f246f2fe-6649-11e7-8bf6-91d78e6b1c40.jpg)
