### ISSUE TITLE
Organisers Page

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#49]
We need an organiser's page added to the website so people know who is behind CampJS. 

At the moment the list goes:
Glen Arrowsmith
Damon Oehlman
Craig Sharkie
Luke Brooker
Adam Brady
Maurice Butler
Anna Gerber
Cathy Lill

Much credit should also be given to Tim Oxley as the original father of CampJS.

**Comment by garrows** [comment]
We should add past organisers too.

**Comment by SomeoneWeird** [comment]
Sounds good.

**Comment by garrows** [comment]
Oh and add @SomeoneWeird  to the list!

**Comment by garrows** [comment]
Please also indicate that we highly encourage public participation and try to organise everything openly in github issues.

**Comment by AnnaGerber** [comment]
Might be a good idea to indicate next to each organiser what they are helping out with (e.g. wifi), or if are a general organiser, so people who need to contact someone know who to reach out to (also add contact details)

You can add me to the list for zine and scheduling

**Comment by garrows** [comment]
Going to publish this list tonight. Is there anybody I have missed or who doesn't want to be listed?

**Comment by garrows** [comment]
@twalve have you got a profile pic of your face for the organisers page? Would be best if you were identifiable.

**Comment by garrows** [comment]
@cathylill do you have a real face profile pic I can use too?

**Comment by garrows** [comment]
I took some liberties on titles. Let me know if there needs to be changes. Still need to do proper profile pictures and update emails.

**Comment by timoxley** [comment]
Perhaps there could be some kind of meta campjs page that gives some overview & history + links to the previous camps' websites.

edit: this is off-topic

**Comment by garrows** [comment]
@timoxley I know its off topic but I think we should break tradition of recreating the website each year. Luke did the design but copying over content was a huge overhead that I could have lived without.

**Comment by garrows** [comment]
Need to add @digitalcraft (Jeff Lynne) too as an the internet/networking organiser

**Comment by twalve** [comment]
I can fix this up tonight!

**Comment by garrows** [comment]
Thank you twalve!
