### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#5]
Prospectus:
https://github.com/campjs/campjs-next/blob/gh-pages/org/sponsorship/campjs_viii_sponsor_plus.pdf

Items to sponsor:
* Busses (Mozilla)
* Coffee (Lookahead Search)
* Drinks
* Internet (Digital8 and possibly TokBox?)
* Swag
* Diversity/disadvantaged tickets (Lookahead Search)
* Possibly childcare (funcaptcha.com)
* Videos (RedBubble)

**Comment by garrows** [comment]
@developersteve is great at getting money from people. I'll buy him a coffee this morning and hopefully that'll turn into a large sum of sponsorship money.

**Comment by DamonOehlman** [comment]
Yep, definitely happy to help coordinate this and continue to put people in touch with people :)

**Comment by developersteve** [comment]
haha just saw this thread, yeah can do some intros and know some local devrel evangelists that are looking for events in the region :)

**Comment by garrows** [comment]
@developersteve great to have you on board. I've granted access to the repo as well so we can collaborate on a sponsorship doc.

A couple of good examples @developersteve has provided (via slack) are: 
https://s3.amazonaws.com/developersteve/wp-content/uploads/2017/04/Sponsorship-Opportunities.pdf
https://kingdomhack.com/wp-content/uploads/2017/04/KingdomHackSponsorDoc2017.pdf

Created a PR https://github.com/campjs/campjs-next/pull/14 that we can get started on.

**Comment by garrows** [comment]
I've closed https://github.com/campjs/campjs-next/pull/14 as it contains a perspectis that @twalve put together a while back. Big thanks to @twalve. 

@developersteve can you have a review of the doc? https://github.com/campjs/campjs-next/blob/gh-pages/org/sponsorship/campjs_viii_sponsor_plus.pdf

@DamonOehlman also reports that RedBubble is shown interest in the past and he is pinging them again now that the wheels are turning.

**Comment by marcoscaceres** [comment]
Lodged request for Foundation sponsorship from Mozilla: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1373529

If it get's knocked back, I'll try for just the buses.

**Comment by garrows** [comment]
Lookahead search is locked in as our first official sponsor! :tada: 
Thanks you @twalve for your hard work!
