### ISSUE TITLE
Add inclusivity info to the website

### ISSUE THREAD

**Issue by AnnaGerber** [campjs/campjs-next#56]
An example of the kind of info that should be visible on the website:

http://2016.cssconf.com.au/2016/07/01/programming-inclusion.html

Was suggested via Twitter from fantastic ms fox

**Comment by DamonOehlman** [comment]
Thanks Anna.  Read the post and all of that sounds awesome.

The only thing in that list that might be difficult to address given some of the venues is the following one:

> Gender neutral restrooms: we want our attendees to make their own decisions on restroom choice, thus we don’t support binary arrangements.

We can definitely try and attempt to source different venues based on that requirement (and let's face it asking the question when approaching venues will help highlight the need for it). I think everything else there is something we can and __should__ address.

**Comment by AnnaGerber** [comment]
BTW this issue is for the task of adding the page to the website.

The link above is an example of an event that has a page that puts all the info in the one place to make it easy to find.  Discussions today make it clear we need a page like this for CampJS.

Let's list all of the info that is current for CampJS (i.e. what we actually do / have).

It would be great to aim for other things too but whether those are achievable with the time and resources available is more of a discussion for #52

**Comment by DamonOehlman** [comment]
So...

### Diversity

> Code of Conduct and its enforcement: all attendees—delegates, speakers, volunteers, sponsors, exhibitors and organizers, are expected to abide by the Code of Conduct. A response team will be formed to assist with any incidents that may arise.

👌  - probably need a more formal response team and a better understanding of how our email address is monitored.

> Scholarship Program: a fixed amount of free tickets will be given out to individuals from underrepresented groups, who couldn’t attend otherwise.

Not something we've really advertised, but can make this happen so I think we should include it with some details on how to access the tickets.

> Purchasable Diversity Supporter Tickets: we’re offering an unlimited set of Diversity Tickets that can be purchased by anyone and donated to the Scholarship Program pool.

Something we should do for the next event.

> Subsidized Student Tickets: students can attend a single event at $230 and all of them at $460 (over 60% cheaper that regular tickets).

Again not something we have done yet.  But I think we should consider doing this even now.  If there have been students that have bought a ticket at a non-student price we can work out how to refund the difference.

> Photography and video policy: colored badge lanyards will be leveraged to indicate individuals’ consent for photo taking.

Love this idea.  Let's do this.  I'll make sure Rodger is across this.  Did you want me to take care of the Lanyards?

> Gender neutral restrooms: we want our attendees to make their own decisions on restroom choice, thus we don’t support binary arrangements.

Lord Somers does not have this.

> Diversity-enabling Call for Papers: we will be using a custom, anonymous Call for Speakers process to facilitate 50/50 women to men ratio.

Next time?

> Diverse community reach-out: we intend on contacting individuals from underrepresented groups to invite them to participate as attendees or presenters, offer coaching in doing so and spread awareness about the events amongst beginner groups.

While this was done to some extent, I don't think we should in anyway attempt to claim that we did this as well as we could; so shouldn't be added to the site.

### Accessibility

> Fully wheelchair accessible: the Meat Market pavilions provide step-free access and we aim to extend that to all party and side event venues.

We should check this. I think Lord Somers is pretty good.

> Visual impairment assisted: preferred seating will be reserved for the visually impaired. Guide dogs are most welcome.

👌  - let's do this and let folks know.

Dietary requirements compliant: allergy-friendly, nutritious and healthy food options will be accessible for all participants accordingly to their specified dietary requirements.

👌  - done and done.  We actually get pretty good feedback on this.

> Speech-to-text transcribed: all talks will be live captioned (drop us an email if you want to help to make that happen!).

If we can find out more info on what is involved with this... maybe?

> Children-friendly: we strongly encourage family participation. A breastfeeding room will be available as well as an option to watch the talks from outside of the main conference hall.

Not this time I believe, but admittedly I didn't stay up to date with the issue thread.

**Comment by AnnaGerber** [comment]
Captioning: http://www.whitecoatcaptioning.com/

**Comment by AnnaGerber** [comment]
One more piece of information that should go on the website (not sure whether on this page or elsewhere on the site) that is specific to CampJS because it's a code retreat rather than a conference, is that we don't have a traditional talk approval/rejection process, other than filtering out obvious spam and not accepting more submissions when we start to run out of slots, as well as putting people in touch with each other who submitted similar proposals to work out if they want to work together or work something out to avoid overlap.

Our talks list is pretty much the list of people who are attending the event who have booked themselves a slice of time to talk about something that they think might be of interest to the community. Sometimes the actual topic they talk about changes based on things they've seen in previous sessions. And there are always additional unscheduled sessions. 

It's not a curated experience like a conference

**Comment by DamonOehlman** [comment]
@AnnaGerber I wonder if we should start a separate issue thread to sort out some wording and bring it back in here once we've got something that people are (generally) happy with.  I definitely agree with what you've outlined above.

**Comment by garrows** [comment]
This looks great! I've got about 40mins free this afternoon so I'll try to get as much in as I can today as a starting point.

**Comment by garrows** [comment]
I updated the twitter bio to reflect its a code retreat as per your suggestion
```
Biannual code retreat (not a conf) bringing together the most awesome JavaScript talent from Australia & worldwide.
```

**Comment by timoxley** [comment]
> Biannual code retreat

This communicates the intent much better. Good.
