### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#6]
Our amazing [vii](http://vii.campjs.com/about/) website was created by the talented @lukebrooker. I understand we are all busy people but @lukebrooker, would you be interested in working on the next site? If so, would you like to start fresh or modify what we already have?

@SomeoneWeird has DNS access for when we are ready.

**Comment by lukebrooker** [comment]
I'll see what I can think of. As usual, I don't have a lot of extra time and I can't attend in July as we have another baby due in July. Worst case we can update the old website with new details.

Conceptually it's not quite the same as it's not on an Island. But it is still near water 😄 

Happy for someone else to pick this up if they are passionate about it. All good to work it out if they don't though.

**Comment by garrows** [comment]
Thanks @lukebrooker. We're looking at putting it on in August so you can bring your family 😃  

Anyone you would like to dob in to help on the site?

**Comment by garrows** [comment]
Sorry @lukebrooker but I cleaned the slate in preparation for IX. I want to get early bird tickets up by the end of the weekend so I needed something basic/ugly. 

@SomeoneWeird can you update the DNS for ix.campjs.com please?

**Comment by SomeoneWeird** [comment]
Aren't we up to viii not ix? :)

**Comment by SomeoneWeird** [comment]
Added viii.campjs.com

**Comment by garrows** [comment]
Indeed we are up to viii.  🤦‍♂️ 
I've fixed it now. Our horrible placeholder landing page is up http://viii.campjs.com/

**Comment by developersteve** [comment]
Actually on that note @garrows thinking about prospectus and marketing came into my mind, thinking a scifi ascii aka a popular star related wars theme (see what i did there)

**Comment by garrows** [comment]
HUGE thanks goes to @lukebrooker for setting up an amazing website for us. You are a hero. 

Some more content needs to be transferred over from last camps but I can do that.
