### ISSUE TITLE
Transport/Buses

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#7]
I believe @timoxley kindly organised the buses for the last Melbourne event. I know it's difficult to organise from Singapore so it'd be good to get some volunteers. 

@timoxley can you dump any information you have?

This [excerpt](http://v.campjs.com/#information) might help with anyone organising the details:
"A bus will be provided to take attendees to and from the venue. It will travel from Tullamarine airport and back via Melbourne CBD. Interstate travellers should fly into Tullamarine airport around midday, busses will leave between 1 and 2pm. The return bus will get people back to the airport before midday."

**Comment by bguiz** [comment]
@garrows I'd suggest nominating a pick up point and time(-ish) for the Melbourne CBD too. Lygon street just off Melbourne Central seems like it is en route, and easy enough to get to by public transport.

**Comment by garrows** [comment]
Good idea @bguiz. I don't suppose we could nominated you to organise the buses completely could we??

**Comment by garrows** [comment]
Jessica Edwards on slack pointed out that web directions code is in Melbourne on the Thursday & Friday of campjs weekend. They end with closing drinks at 5.30pm Friday. If there is enough people going to both, we should attempt to organise transport between the two.

**Comment by jsscclr** [comment]
Hi! There might not be a whole lot of people attending both Code and CampJS, but I'm sure there are quite  a few who work in Melbourne that would prefer not to take leave for the Friday.

**Comment by garrows** [comment]
Started getting quotes for busses. 

Quote 1:
 www.kastoria.com.au 2 x 50 seat @ $660, per coach, each way, total of $2,640, includes GST.  This is based on direct transfers only.

Quote 2:
venturabus.com.au 2 x 50 seat @ $898.83, per coach, each way, total of $3,595.32, includes GST.

Quote 3: 
melbournebuscompany.com.au 2 x 57 @ $1600.00 + GST per coach, total of  $3,520.00 incl. GST

**Comment by garrows** [comment]
Depending on numbers/demand I might have to book a 3rd coach or a minibus.

**Comment by garrows** [comment]
Kastoria has 21 seater + luggage trailer for $525 each way. Might be a good option for a final bus leaving around 6pm to catch people not taking the day off work and transfers from Web Directions.

**Comment by Bondifrench** [comment]
Hi all,

what is the cut off time for buses leaving Tullamarine on Friday? and what's your plan for buses on Monday when coming back?
Coming from Sydney, it seems there is a Jetstar arriving on Friday at 1.50pm or is it too late? the next one arrives at 2.20pm.

On Friday, there seems to be some Tiger Air leaving Tullamarine at either 7.55am or 10.10am, what time would you target for buses to arrive?

**Comment by garrows** [comment]
Hi @Bondifrench 

The plan was to leave the airport 2pm Friday. I can get the 2nd bus to leave at 3pm as well if you think there'll be a fair few people on that flight.

There will be a 3rd bus leaving at after Web Directions Code closes at 5.30pm from [The Pavilion](https://www.google.com.au/maps/place/The+Pavilion/@-37.8214528,144.9684172,15z/data=!4m5!3m4!1s0x0:0x8b6404a17524fd20!8m2!3d-37.8214528!4d144.9684172).

As for Monday, we there'll be 2 busses. One will leave at 10am to get to the airport around 11.30am. There is usually an earlier bus but I'm not sure what time that has left in the past. How does leaving at 7am sound?

**Comment by Bondifrench** [comment]
Sorry for the late answer, leaving at 7am sounds perfect.

**Comment by garrows** [comment]
This is what I've just requested a booking for. The Monday morning coaches might get over bookeded but based on ticket sale's answers, it looks fine.

Bus: 50 Seater Coach
From: Tullamarine Airport 
To: Lord Somers Camp, Cnr of Lord Somers Rd and Parklands Avenue, Somers VIC 3927
Pickup stop: Russell Court
Start: 1.00pm 4th August

Bus: 50 Seater Coach
From: Tullamarine Airport 
To: Lord Somers Camp, Cnr of Lord Somers Rd and Parklands Avenue, Somers VIC 3927
Pickup stop: Russell Court
Start: 2.00pm 4th August

Bus: 50 Seater Coach
From: The Pavilion, 100 St Kilda Rd
To: Lord Somers Camp, Cnr of Lord Somers Rd and Parklands Avenue, Somers VIC 3927
Pickup stop: Russell Court
Start: 5.30pm 4th August

Bus: 50 Seater Coach
From: Lord Somers Camp, Cnr of Lord Somers Rd and Parklands Avenue, Somers VIC 3927
To: Tullamarine Airport
Dropoff stop: Russell Court
Start: 7.00am 7th August

Bus: 50 Seater Coach
From: Lord Somers Camp, Cnr of Lord Somers Rd and Parklands Avenue, Somers VIC 3927
To: Tullamarine Airport
Dropoff stop: Russell Court
Start: 9.30am 7th August

**Comment by garrows** [comment]
This is the Russel Court I was referring to which doesn't look like it's a court anymore....
https://www.google.com.au/maps/place/Federation+Square+Bus+Loop/@-37.8168135,144.9703966,18z/data=!4m13!1m7!3m6!1s0x6ad642c99e207041:0xc358d059bfe29278!2sRussell+St,+Melbourne+VIC!3b1!8m2!3d-37.8119251!4d144.9676339!3m4!1s0x0:0xf2ccbfb329ad42c5!8m2!3d-37.8172078!4d144.9701692
