### ISSUE TITLE
Intranet Emergency Contact System

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#77]
Looking for a way that someone on the local intranet could contact the organisers in case of emergency. 

It must not require any external resources in case the internet is down. 

The intent is to improve safety after @alexiamcdonald fell down some stairs and wasn't able to contact anyone via phone or wifi and had to wait 10 minutes before someone heard her. https://github.com/campjs/campjs-next/issues/52#issuecomment-313036406

**Comment by garrows** [comment]
It's been pointed out that the incident was at the Sydney venue and the Melb venue has much better mobile coverage so 000 should work. I'll try to check with the venue though. 

It'd still be cool to have an intranet chat method though.

**Comment by cathylill** [comment]
https://www.opengarden.com/firechat.html maybe?

**Comment by garrows** [comment]
@cathylill good suggestion. I think I'll close this one and just put firechat on the recommended installs list https://github.com/campjs/campjs-next/issues/41
