### ISSUE TITLE
Bar Staff

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#79]
This camp we are going to have a bar serving free beer & wine staffed an RSA certified bartender. 

We chose this option because there are several inclusivity issues with the previous event's supplied alcohol method and there has been even more issues the time we just did BYO. Note small amounts of BYO alcohol are permitted. See http://viii.campjs.com/food/ for more details.

Jodie Arrowsmith (my lovely wife) has kindly volunteered to staff the bar from lunch to dinner. I'll get my RSA as well to help out. I'd appreciate some more volunteers as well.

I have a quote from mmbars.com.au that comes to approximately $815 which we should be able to cover.

Looking for more quotes for 7pm to 11pm Friday, Saturday & Sunday night.

**Comment by twalve** [comment]
I used to be RSA certified. Happy to get that reestablished if possible?

**Comment by garrows** [comment]
@twalve yes! That'd be great. Thanks!

**Comment by garrows** [comment]
Ive hired someone from http://www.zestbars.com.au/ for Saturday & Sunday night for $50/hr with no callout fee from 7pm to 11pm ($400 total). 

Jodie wont be able to staff the bar during the day anymore but I think that daytime unstaffed is fine. 

@twalve can you help me staff it on Friday night please?
