### ISSUE TITLE
Add locations for bus pick up points to website

### ISSUE THREAD

**Issue by AnnaGerber** [campjs/campjs-next#84]
Based on comment that come in on viewsource campjs slack: 

would be good to have the exact locations (perhaps a map) for the bus pick up / drop off points on the website

Related to #7

**Comment by twalve** [comment]
I've contacted both Avalon Airport and the Arts Centre for details on where we can park a bus for pick-ups. Will update the page when that data comes through

**Comment by garrows** [comment]
Thanks @twalve. Tullamarine airport is the one you want. Not many flights go to Avalon so we've never sent a bus there. 

Also, this was the CBD pickup point last time
Federation Square Bus Loop
Russell Ct, Melbourne VIC 3000
https://goo.gl/maps/cHryLW32dHu

**Comment by garrows** [comment]
This is the CBD pickup point. Same as last Melbourne camp. 

https://www.google.com.au/maps/place/Federation+Square+Bus+Loop/@-37.8168135,144.9703966,18z/data=!4m13!1m7!3m6!1s0x6ad642c99e207041:0xc358d059bfe29278!2sRussell+St,+Melbourne+VIC!3b1!8m2!3d-37.8119251!4d144.9676339!3m4!1s0x0:0xf2ccbfb329ad42c5!8m2!3d-37.8172078!4d144.9701692

**Comment by garrows** [comment]
Called Tullamarine airport. This is exactly where charted busses pick people up.
https://goo.gl/maps/cVzEvD7tq9k

**Comment by garrows** [comment]
Web Directions Code meeting point https://goo.gl/maps/f3MBGxpCakE2
