### ISSUE TITLE
PA & Projector Hire

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#86]
Not sure where we've hired this from in the past. Can anyone help with gathering quotes?

@rvagg?

**Comment by AnnaGerber** [comment]
As soon as we know what projectors are being used, it would be good to be able to update the speakers on the resolution(s) supported.

**Comment by thissophie** [comment]
@garrows mentioned "Hire 5 x Projectors & screens ($600 including delivery from projectorhiremelbourne.com) Need to upgrade projectors" in #91 

Has anyone picked this up, or can I help out by making some calls to get some quotes?

I'm guessing we'll also need a speaker + mixer + mic(s) for each space as well (maybe not the workshop room(s)).

**Comment by garrows** [comment]
@thepatrick Thank you!!!
Yes we will need that too. I don't have any details on what we got last time unfortunately.

**Comment by thissophie** [comment]
djwarehouse (who I think we used for the Sydney-ish camp last year):

For the main hall & the two talks areas: https://www.djwarehouse.com.au/collections/party-hire/products/jbl-prx-100-sound-system ($89 w/ mixer, add $20 for 2 microphones)

For the workshops area: https://www.djwarehouse.com.au/collections/microphones/products/microphone-pa-100-system  ($79, 1 speaker + microphone, particularly useful if any of the workshops needs sound output)

Projector w/ screen: $160 each

Delivery/Pickup: TBC

**Comment by thissophie** [comment]
pojectorhiremelbourne.com

Full HD 4000 Projectors = $160
80" Pull Up Screens = $40

1000W PA Speakers = $80
700W PA Speaker = $40
Speaker stands $10

Microphones $10

**Comment by garrows** [comment]
Thanks @thepatrick. I'll confirm what the venue has then can you get an invoice? Also we had 100" screens last melbourne but not sure if 20" is a deal breaker or not.

**Comment by thissophie** [comment]
projectorhiremelbourne.com are $40 for a 100" tripod screen, or $60 for a 100" pull up, so we could go to the tripod for no extra cost.

**Comment by thissophie** [comment]
Do we have someone who can pick things up on Friday / drop them back on the Monday? I'd do it but I can't drive a car 😀

**Comment by garrows** [comment]
Do they offer delivery per chance? I doubt everything will fit in 1 car anyway.

**Comment by thissophie** [comment]
Just finished speaking with projecthiremelbourne.com.au, he's sending through a quote but invoice is provided on the day of pickup/delivery.

I've asked him to quote deliery as well.

This is the verbal quote:

3 x 1080p projectors = $420
2 x 720p projectors = $240
5 x 100" tripod screens = $100
4 x 15" active speakers, with stands = $200
4 x microphones = $40

**Comment by thissophie** [comment]
Ok, total is $1000 (as above) + $200 for delivery & pick up.

I've booked in the hire itself (because it can be canceled, and didn't require any payment).

**Comment by thissophie** [comment]
Quote is here https://github.com/campjs/campjs-next/pull/92

**Comment by thissophie** [comment]
Pulled from #92 - delivery will be on Friday between 2-3PM.

**Comment by garrows** [comment]
Hey @thepatrick sorry to do this but can you change the order? I spoke with the venue and they have projectors in the main hall (old VGA ones), a PA system and screens. Looks like we'll need:
3 x 1080p projectors
3 x 100" tripod screens
3 x 15" active speakers, with stands
3 x microphones

Sorry about the change. It's' hard to get a hold of the venue. 


@AnnaGerber you can tell the speakers that the projectors will be 1080p. For the final presentations on Sunday night I'll swap out the old projector for one of the new ones so they still get 1080p.

**Comment by thissophie** [comment]
@garrows I've sent that request through, will update when I get confirmation

**Comment by thissophie** [comment]
Response:

> not a problem..$860 in total with delivery and pick up service included!

**Comment by DamonOehlman** [comment]
@thepatrick @garrows when we get an invoice for this just drop it in as per the normal format, and I'll make the transfer across :)

**Comment by garrows** [comment]
Awesome! Thanks @thepatrick.
