### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#9]
I see we have fork of OpenCFP. Has this worked well in the past?

**Comment by joshwnj** [comment]
I haven't used it from an organiser's point of view, but I used it to submit to the last campjs and it was a pleasant experience.

**Comment by DamonOehlman** [comment]
Yeah, I think it worked pretty well.  The main thing at that time that was lacking (IIRC) was a good way to provide submission reviewers access to the submissions with the speaker details removed. IMO it's important that a submission is reviewed based on the merits of the submission not the speaker's profile (or other aspects).

The project is still under active development though, so they might have added this feature.  And to be honest, it wasn't that hard to produce a list of blind topics for people to review.

**Comment by DamonOehlman** [comment]
Also, from what I recall set up on Digital Ocean was pretty easy too.

**Comment by garrows** [comment]
Thanks for the feedback @damonoehlman. Despite this I've gone with creating a simple google form. I'll share the submissions once I've figured out how to automatically anonymise them. 

https://goo.gl/forms/cxUh8JrQccUBzw992

Tweeted it https://twitter.com/campjsnews/status/859773266151448577 and added the link to the website. I'll also PM some people I know are interested.

**Comment by cmf** [comment]
One thing that would be good to specify is whether there's any financial remuneration for accepted speakers. I'd have to come from NZ and it's probably too much of an investment to pay the whole trip myself. I assume speakers get free conference access? It's also not clear how the accommodation works for those of us that are unfamiliar with the event - is accommodation provided for speakers? Is this actually camping, i.e. would I have to bring a tent? Enquiring minds want to know :-)

**Comment by garrows** [comment]
Thanks @cmf. At this point I'm unsure what we can offer regarding remuneration. Waiting on more quotes, estimates and sponsorships before we can promise anything. Sorry for being unclear. We will do our best to accommodate speakers though. 

Regarding the accommodation, no tent required as there are dorms. We still need to put all the information up on the new site but you can look at past camps for more info http://v.campjs.com. Ticket release was initially targeted at previous attendees who knew all this already. Momentum and excitement was higher than expected so we are playing catch-up now. Sorry for causing confusion.

**Comment by cmf** [comment]
@garrows No problem, thanks for the info.

**Comment by garrows** [comment]
We have 9 talk submissions so far. Pretty good response IMHO. 
Still haven't figured out a nice way to anonymise and vote on them.

**Comment by DamonOehlman** [comment]
@garrows probably worth editing your comment above and `s/speakers/talk submissions/`

**Comment by garrows** [comment]
Talks have dried up. Not getting any more submissions despite some tweets asking for talks. Can anyone please help me drum up some more interest?

https://docs.google.com/forms/d/e/1FAIpQLScBE0oz48Y4KlJVF7ePeC20sJSv8Ou_5xaNHSxuo5uw7yap-w/viewform?c=0&w=1

**Comment by DamonOehlman** [comment]
@garrows did you still want more submissions, I can tweet it if you like.  Additionally, I've been putting pressure on a couple of Canva folks to submit talks (and if I'm feeling keen I might submit one as well).

**Comment by garrows** [comment]
@DamonOehlman certainly do! Cheers.
