### ISSUE TITLE
Final Issues

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#91]
Got a great information dump from Tim. Writing down here so it's not lost in slack history.

Before Friday
- [x] Hire fridges 2 x 2 glass door ($770 including delivery from exhire.com.au)
- [x] Zine intro text
- [x] Find bus contact people
- [x] Certified First Aid Person
- [x] Check sponsor agreements met
- [x] Hire heaters ($206 last time for around 3. Venue organised last time)
- [ ] Hire lecterns
- [ ] Get swag from Marcos
- [ ] Bathroom signs
- [ ] Dedicated snorer's quarters
- [ ] Opening & closing presentations. Include hashtag, share photos to g+, code of conduct, encourage bloggers. 

During the weekend
- [ ] Assign chief fridge stocker. Make sure wrappers are removed. 
- [ ] Ensure someone to clean & remove rubbish each morning. 
- [ ] Announce next camp at the end 
- [ ] Announce each talk in the main hall 
- [ ] Keep schedule publicly visible
- [ ] Exchange table
- [ ] Schedule a supermarket trip. Have a book for people to write a list in.

**Comment by AnnaGerber** [comment]
I spoke to @iamkevinv about being a bus contact person today, now that he has booked his flights 🎉

**Comment by iamkevinv** [comment]
Yep I'm scheduled to be there before the first bus at 1pm. Let me know how I can help.
