### ISSUE TITLE
Lanyards & Name Tags

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#94]
Spoke with @MauriceButler and he kindly volunteered. 
Needs to have organiser's phone numbers in case of emergency and code of conduct violations. 
Dont forget the viii.campjs.com/sponsors (not the speaker sponsors)

**Comment by MauriceButler** [comment]
Tracking down cheap lanyards etc has been done. getting from https://www.aacidsolutions.com.au

Invoice #100 

I still need to sort the actual paper / cardboard etc to go into the sleeves

**Comment by garrows** [comment]
Thanks again @MauriceButler. I hear you've even sorted out the printing too so I'll close this.
