### ISSUE TITLE
Shopping List

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-next#95]
- Towels 
- Soap
- Toothbrushes
- Toothpaste 
- Juice
- Flavoured milk 
- Ginger beer
- Fruit
- Nuts
- Bottled water
- Bottle openers
- Cups
- Wine cups
- Tea
- Glow sticks
- USB sticks
- First aid kit?
- Small stickers for ID checks
- Deodorant
- Shampoo
- Pads
- Tampons
- Baby wipes

**Comment by AnnaGerber** [comment]
Also from the inclusivity discussions, bathroom basics:
- deodorant
- shampoo
- pads
- tampons
- baby wipes 

- Colored dot stickers for indicating photography ok / not ok on lanyards
- ear plugs

Will there be coffee pod machines?
- coffee pods
- decaf coffee pods

- milo
- soy milk

**Comment by garrows** [comment]
Thanks @AnnaGerber. Coffee is sponsored by Lookahead so they are handling that. 
Earplugs & photography stuff is already sorted.

**Comment by garrows** [comment]
Sorted by a woolies order https://github.com/campjs/campjs-next/pull/107
